##########################################  Ansible roles   #################################################

Apache: role for apache
       - whatever is required for apache to run will be in the role.
	   
Role: is pre-defind structure which should be used to configured any appication.

#ansible-galaxy init apache --offline -> use for to creating a structure.

components of roles:

defaults: it provide the data about the role/application.default variables will be stored in this folder.
files:    put the static files here.
Handlers: kind of refresh or trigger .Tasks which are based on some actions.A Handler is exactly the same as a Task, but it will run when called by another Task.
          - In case my http.conf changes,it should trigger service restart.
		      - This is useful for secondary actions that might be required after running a Task, such as starting a new service after installation or reloading a service after a configuration change.
		  
meta:     it tells about the role, information about the role like Author name,supported platforms etc...Dependencies , if any
tasks:    actions are stored , core logic or code .Installing packages,coping files etc..
Templates : will be stored in the dynamic files -> similar to files except that templates support dynamic files.
vars:     both vars and defaults stores variables.variables stored under "vars" has got high priority.


##############   project sample #########################

#cd tasks -> vim main.yml file
- include: install.yml
- include: configure.yml
- include: service.yml

incide tasks: vim install.yml
---
- name: install apache
  apt: pkg=apache2 state=present
	
incide tasks: vim configure.yml
---
- name: apache2.conf
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
   - restart apache service
- name: send index.html
  copy: src=index.html dest=/var/www/html/index.html

incide tasks: vim service.yml
---
- name: start apache service
  service: name=apache2 state=started

includede files: #cp /etc/apache2/apache2.conf .
              #vim apache2.conf ->modified ansible file

              #vim index.html --> edit sample file
			  <html>
			  <h1> Learning ansible roles </h1>
			  </html>

incide handlers: #vim main.yml
---
- name: restart apache service
  service: name=apache2 state=restarted

incide /etc/ansible: create site.yml file
#vim site.yml
---
- hosts: webserver
  sudo: yes
  roles: 
    - apache
	
To check syntax : #ansible-playbook site.yml --syntax-check



	

